/*
 * This source file was generated by the Gradle 'init' task
 */
package com.matthewjohnson42.dataanalytics;

import org.junit.jupiter.api.Test;

class DataAnalyticsDataServiceTest {

    @Test
    void canInstantiate() {
        DataAnalyticsDataService classUnderTest = new DataAnalyticsDataService();
    }

}
