/*
 * This source file was generated by the Gradle 'init' task
 */
package com.matthewjohnson42.dataanalytics;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class DataAnalyticsDataService {

    public static void main(String[] args) {
        SpringApplication.run(DataAnalyticsDataService.class);
    }

}
